language: ruby
sudo: false
rvm:
- 2.3.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script: ./script/cibuild
deploy:
  provider: script
  script: ./script/cideploy
  skip_cleanup: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_dd48d451c1d3_key -iv $encrypted_dd48d451c1d3_iv
  -in script/deploy_id_rsa.enc -out deploy_id_rsa -d
notifications:
  slack:
    secure: WHr6xCLGLTAfcTgLYFUxeA02Wuuevuw5v7kB3qYu0/8pV/xPxQMmVB+lGr9zSGasDMvUxYfHdNKWjjuloDkRcDjtV4Y2YtV8b/lFU9sR/lbaG+b/E4YUTaexYPaSGZnhrZDh9wyJgeqAQNrgGHw162DiNtCc6IM/b3cu3db30mOMge17rzyTayDc5zd07qV0IeDtzsbIl6DW6jK2RDfJnosrJC4Pzv98RSMB0d00d2pXRcW/gf+KVxVpXySjlLluAgnI7uFNbou92hTxxV/loPV5/lQI8hYIFUFW3iS5oXASeUTsxJ/DZeTGIO86br7Wh6Bbpwofl1aW5zODsPBB5V05u2HYo8yIDXgqSaCgRjgrfy42PLr1zavbjdpTYFdtaghVtPnIn8VMlV3GU6+xec37SoT4d5Ke+XCPKmNFnZ7HBdR2niGLV1HKqXJ0WMj7v9Ynq03vfFjC3V+SgZLKZ8t63gtpfdnGeUJCS2bDqRZg7xlqeRt3l0nyN3Mj0gIV2mCzB+0rn2lpQYegalG8vI73YsARGsWLqPZvHpNnWIEtuK95m732qnitWrfLkL5zCRq4maVB+rHQ6WGD5ts+kyIuDN66SedyqFxFDpsfOzebJilt1YRRJCwaajrdslWFV/vjJBtuxh8ghepND2Kd6KtBtVMd9pTPc8p/rI4wkew=
