language: ruby
sudo: false
rvm:
- 2.3.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script: ./script/cibuild
deploy:
  provider: script
  script: ./script/cideploy
  skip_cleanup: true
notifications:
  slack:
    secure: SrBWCIirC7NygrGd6qa9Yz1hfCg5M6lK9zxStQx/LgVC2ytsbWy9QgVwdQm95CkLX6SSjN5Ya9JIvnt/Sa+uQ+0NTvCqV4DZihOuhPzbbZl+roQGLRd9goYiib9dN2StWj9CnIxHqT5LPkj2rlvEyZBlCkVUlyTSZlVdOR3FaHwPnxjNsmH1t0/3ifF9u8Rgu6swRKgXASLRSwKtq0suabrAS57vh071CdSOCV9LjxDYQUqMNAm3UCyoacm2lbG4AQVJSBp3BQRZI6xwosTvuiuVH7+WpLHzhDkekwkLNHQsAamz2qXe0tXk/g4yBoLLSo+5Cu4ZieRlE1rlko8cZyj4gDJnPVg+e+hj2xvirSwMf8juhbwHXhC16x7iCEu0hXEJcfcNaKbS43NeHUWhtkZHF9Y0ZfOzNcMqG2divxNItzgsZ17ovjDKA4cktPwQeSKvzKkv6lOqs4NLP8btgZHAokF7eA2y3EzwYBqtIqbX49MZflcfZbKzXMUwrwNMbSXlt2ZYPUto1DgodTVbe5gY7HWuH2ObaNuU383p2yFeIUUIj53TBOgmwkcV2Zz0yPmc2h6CIO76mJUKvHmEaoJpNbeNGpYCVHskmzZB/dV7eJpHipuJnHoJRdyLnF0kan+kxgVKfu5eYwH5m3BzggRWf+uSZXy1JyqRV6+hidQ=
before_deploy:
- openssl aes-256-cbc -K $encrypted_1b8e1d403d94_key -iv $encrypted_1b8e1d403d94_iv
  -in script/deploy_id_rsa.enc -out deploy_id_rsa -d
